import pygame

SCREEN_WIDTH = 1080
SCREEN_HEIGHT = 720
MAX_FPS = 60 #60
FLAGS = pygame.RESIZABLE

DECK_NUM = 6 #Blackjack can be played with a collection of two to six decks of french cards
DEALED_CARD_POSSIBLE_ROTATION = (-40, 40)
DEALED_CARD_POSSIBLE_X_OFFSET_RANGE = (-250, 250)
DEALED_CARD_POSSIBLE_Y_OFFSET = 25
MAX_THROWN_CARD_VELOCITY = 10